alias c="clear"
alias cdp="cd ~/Projects/"
alias cdc="cd ~/Configs"
alias cdn="cd ~/Notes"
alias clip="xclip -selection clipboard"
alias d='docker'
alias docker-compose='docker compose'
alias k='kubectl'
alias h='helm'
alias hf='helmfile'
alias t='terraform'
alias cl='clear'
alias lg='lazygit'
